#Spencer Krum
#Collatz Conjecture pickle renderer w/ pylab and class

from pylab import *
from matplotlib import *

import pickle
import gzip

filename = raw_input("Please give the path to the pickled object generated by the sister program: ")
name = raw_input("Please give the name of the file you would like to save the resulting graph in: ")

class Collatz:
	def __init__(self, start, end, highwater,blank):
		self.start = start
		self.end = end
		self.highwater = highwater
		self.blank = blank


#picklefile = open(filename, 'r')
picklefile = gzip.open('/home/nibz/Documents/drakepy/pickle.gz', 'w') 
pickleobject = pickle.load(picklefile)




ion()
plot(pickleobject.blank, pickleobject.highwater, '.')
ylabel('Number of steps to one')
xlabel('Initial number')
grid(True)
draw()
hold(False)
savefig(name)
raw_input("Press return to quit")
